# Exemplos com NumPy Arrays


In [12]:
import numpy as np

# Criando um array a partir de uma lista
numeros = np.array([1, 2, 3, 4, 5])
print(numeros)
print(type(numeros))
print('-'*30)

# Criando um array de zeros
zeros = np.zeros(10)
print(zeros)
print(type(zeros))
print('-'*30)

# Criando um array de zeros, com a dimensão determinada (2 linhas e 3 colunas)
dimensao = (2, 3)
zeros = np.zeros(dimensao)
print(zeros)
print('-'*30)

# Criando um array de uns
uns = np.ones(10)
print(uns)
print(type(uns))
print('-'*30)

# Criando um array de números aleatórios
aleatorios = np.random.rand(5)
print(aleatorios)
print(type(aleatorios))
print('-'*30)


[1 2 3 4 5]
<class 'numpy.ndarray'>
------------------------------
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
------------------------------
[0.24568124 0.97129382 0.45276007 0.19380401 0.54847974]
<class 'numpy.ndarray'>
------------------------------


In [13]:
# Criando um array de zeros
zeros = np.zeros(100_000_000)
print(zeros)
print('-'*30)

# Criando um array bidimensional de zeros, com a dimensão determinada (20000 linhas e 30000 colunas)
dimensao = (20_000, 30_000)
zeros = np.zeros(dimensao)
print(zeros)
print('-'*30)

# Criando um array de uns
uns = np.ones(100_000_000)
print(uns)
print('-'*30)

# Criando um array de números aleatórios
aleatorios = np.random.rand(100_000_000)
print(aleatorios)
print('-'*30)


[0. 0. 0. ... 0. 0. 0.]
------------------------------
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
------------------------------
[1. 1. 1. ... 1. 1. 1.]
------------------------------
[0.34243805 0.72128611 0.18392285 ... 0.94352264 0.71549875 0.66007801]
------------------------------


### **Tipos de Arrays com numpy:** `int32`, `float64`, `bool`

In [9]:
# Criando um array de inteiros
ndarray = np.array([10, 20, 30], dtype=np.ndarray)

# Criando um array de inteiros
inteiros = np.array([10, 20, 30], dtype=np.int32)

# Criando um array de números reais
reais = np.array([1.5, 3.2, 4.7], dtype=np.float64)

### **Tipo de Array:** `ndarray`

A partir de uma lista de números usando a função np.array() para converter a lista em um ndarray

In [11]:
# Lista de números
lista = [1, 2, 3, 4, 5]

# Criando um ndarray a partir da lista
ndarray = np.array(lista)

print(ndarray)
print(type(ndarray))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Criando um ndarray com valores específicos:
Criamos um ndarray diretamente da lista de valores desejados.

In [14]:
valores = [5, 10, 15, 20]

# Criando um ndarray a partir dos valores
ndarray = np.array(valores)

print(ndarray)

[ 5 10 15 20]


### Outros exemplos com NumPy

In [25]:
# np.random.rand() para gerar números aleatórios.

# Criando um ndarray com arange, parecido com range
ndarray = np.arange(4,17,2)
print(ndarray)
print()

# Criando um ndarray com valores float
ndarray_float = np.arange(0, 5, 0.5, dtype=np.float64)
print(ndarray_float)
print()

# Criando um ndarray com valores complexos
ndarray_complex = np.arange(0, 5, 0.5j, dtype=np.complex128)
print(ndarray_complex)
print()

# Criando um ndarray 2D com valores de 0 a 4 nas linhas e 0 a 2 nas colunas
ndarray = np.arange(0, 6, 1).reshape(2, 3)
print(ndarray)
print()

print("# PROVOCANDO UM ERRO o reshape não consegue neste formato")
ndarray = np.arange(0, 5, 1).reshape(2, 3)
print(ndarray)
print()

[ 4  6  8 10 12 14 16]

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]

[]

[[0 1 2]
 [3 4 5]]

# PROVOCANDO UM ERRO o reshape não consegue neste formato


ValueError: cannot reshape array of size 5 into shape (2,3)

### Manipulação de Forma e Estrutura de Arrays

In [21]:
# Criando um array 2D
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(matriz)
print('-'*30)

# Acessando elementos de uma matriz
elemento_matriz = matriz[1, 2]
print(elemento_matriz)
print('-'*30)

# Verificando a forma do array
forma_array = matriz.shape
print(forma_array)
print('-'*30)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------
6
------------------------------
(3, 3)
------------------------------


### Cálculos da Estatística Descritiva de uma tabela de dados armazenada em NumPy Array: np.mean, np.median, np.std, np.corrcoef, np.cov

In [44]:
# Exemplo de dados com idades de uma turma de aspirantes
dados = [17, 25, 18, 22, 19, 17, 19, 20, 21, 17, 25, 17, 35, 25, 18, 20, 22, 19, 18]
ndados = np.array(dados)

# Calculando a média do array
media = np.mean(ndados)
print("Média das idades", media)
print("-"*30)
print()

# Calculando o desvio padrão do array
desvio_padrao = np.std(ndados)
print("Desvio Padrão das idades", desvio_padrao)
print("-"*30)
print()

# Dados de exemplo para calcular correlação entre 2 variáveis aleatórias
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 5, 4, 5])

# Calculando o coeficiente de correlação
print("Cálculo do coeficiente de correlação")
matriz_correlacao = np.corrcoef(x, y)
print(matriz_correlacao)
print("-"*30)
print()

# Calculando a matriz de covariância
print("Calculando a matriz de covariância")
matriz_covariancia = np.cov(x, y)
print(matriz_covariancia)
print("-"*30)
print()


Média das idades 20.736842105263158
------------------------------

Desvio Padrão das idades 4.290038709961017
------------------------------

Cálculo do coeficiente de correlação
[[1.         0.77459667]
 [0.77459667 1.        ]]
------------------------------

Calculando a matriz de covariância
[[2.5 1.5]
 [1.5 1.5]]
------------------------------



### métodos reshape ravel transpose

In [42]:
# Array original
array_original = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Redimensionando para (3, 3)
array_redimensionado = np.reshape(array_original, (3, 3))
print("Redimensionado com reshape")
print(array_redimensionado)
print('-'*30)
print()

# Redimensionando para um array unidimensional
ndarray = np.arange(0, 12, 1).reshape(3, 4)
array_unido = np.ravel(ndarray)
print(ndarray)
print("Redimensionado unidimensional com ravel")
print(array_unido)
print('-'*30)
print()

# Array original
array_original = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Transpondo o array
array_transposto = np.transpose(array_original)

print('Matriz transposta')
print(array_transposto)
print('-'*30)
print()

# Array original
array_original = np.array([5, 2, 4, 1, 3])

# Ordenando o array em ordem crescente
array_ordenado = np.sort(array_original)
print("Array ordenado usando método sort")
print(array_ordenado)
print('-'* 30)
print()

# Array original
array_original = np.array([1, 2, 3, 4, 5])

# Criando um novo array com valores maiores que 3
array_filtrado = np.where(array_original > 3, array_original, 0)

print("Filtro where")
print(array_filtrado)
print('-'* 30)
print()

# Array com valores repetidos usar unique para eliminar repetidos e contar
array_original = np.array([1, 2, 1, 3, 2, 4, 5])
print("Array original para eliminar repetições", array_original)

# Encontrando elementos únicos
elementos_unicos, counts = np.unique(array_original, return_counts=True)

print("Elementos Únicos", elementos_unicos)
print("Contagem de repetições", counts)
print('-'*30)
print()

# Create a sample array with zeros and non-zeros
array = np.array([0, 1, 3, 0, 4, 0, 5])
print("Vetor original", array)

# Count the number of non-zero elements
non_zero_count = np.count_nonzero(array)

print("Contagem de elementos não zerados")
print(non_zero_count)
print('-'* 30)
print()

# Create a 2D array
array_2d = np.array([[1, 2, 0], [0, 4, 5]])

# Count non-zero elements along columns (axis=0)
non_zero_cols = np.count_nonzero(array_2d, axis=0)

# Count non-zero elements along rows (axis=1)
non_zero_rows = np.count_nonzero(array_2d, axis=1)

print("Contagem de elementos não zerados nas colunas")
print(non_zero_cols)
print('-'* 30)
print()

print("Contagem de elementos não zerados nas linhas")
print(non_zero_rows)
print('-'* 30)
print()

# Count elements greater than 2
condition = array > 2
count_gt_2 = np.count_nonzero(condition)

print("Contagem de elementos com uma condição")
print(count_gt_2)
print('-'* 30)
print()


Redimensionado com reshape
[[1 2 3]
 [4 5 6]
 [7 8 9]]
------------------------------

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Redimensionado unidimensional com ravel
[ 0  1  2  3  4  5  6  7  8  9 10 11]
------------------------------

Matriz transposta
[[1 4 7]
 [2 5 8]
 [3 6 9]]
------------------------------

Array ordenado usando método sort
[1 2 3 4 5]
------------------------------

Filtro where
[0 0 0 4 5]
------------------------------

Array original para eliminar repetições [1 2 1 3 2 4 5]
Elementos Únicos [1 2 3 4 5]
Contagem de repetições [2 2 1 1 1]
------------------------------

Vetor original [0 1 3 0 4 0 5]
Contagem de elementos não zerados
4
------------------------------

Contagem de elementos não zerados nas colunas
[1 2 1]
------------------------------

Contagem de elementos não zerados nas linhas
[2 2]
------------------------------

Contagem de elementos com uma condição
3
------------------------------



### Juntar, dividir e empilhar arrays de forma eficiente

In [34]:
# Arrays a serem concatenados
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenando arrays horizontalmente
array_conct_h = np.concatenate((array1, array2))

print("Concatenando arrays horizontalmente")
print(array_conct_h)
print('-'*30)
print()

# Arrays a serem concatenados
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenando arrays verticalmente
array_conct_v = np.concatenate((array1, array2), axis=0)

print("Concatenando arrays verticalmente")
print(array_conct_v)
print('-'*30)
print()

# Arrays a serem concatenados
array1 = np.array([1, 2, 3])
array2 = np.array([[4, 5]])

# Concatenando arrays com diferentes formatos (axis=None)
array_conct_geral = np.concatenate((array1, array2), axis=None)

print("Concatenando arrays com diferentes formatos")
print(array_conct_geral)
print('-'*30)
print()


Concatenando arrays horizontalmente
[1 2 3 4 5 6]
------------------------------

Concatenando arrays verticalmente
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------------------------------

Concatenando arrays com diferentes formatos
[1 2 3 4 5]
------------------------------



# O NumPy também oferece as funções np.hstack() e np.vstack() para concatenar arrays na horizontal e vertical, respectivamente.

In [ ]:
np.hstack()
np.vstack()

### Dividir um array em partes iguais

In [35]:
# Array original
array_original = np.array([1, 2, 3, 4, 5, 6])

# Dividindo o array em 3 partes iguais
arrays_divididos = np.split(array_original, 3)

print()
print("arrays em partes iguais")
print(arrays_divididos)
print('-'*30)
print()


arrays em partes iguais
[array([1, 2]), array([3, 4]), array([5, 6])]
------------------------------



# Lembrar que já usamos muito o split na leitura de dados de uma linha, e "split" picotamos o texto de uma linha com os pedaços separados por branco ou separados por vírgula

## Empilhar arrays

In [37]:
# Empilhar arrays na vertical

# Arrays a serem empilhados
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Empilhando arrays verticalmente
array_empilhado_v = np.stack((array1, array2), axis=0)

print("Empilhando arrays verticalmente")
print(array_empilhado_v)
print('-'*30)
print()

# Empilhando arrays horizontalmente
array_empilhado_h = np.stack((array1, array2), axis=1)

print("Empilhando arrays horizontalmente")
print(array_empilhado_h)
print('-'*30)
print()

Empilhando arrays verticalmente
[[1 2 3]
 [4 5 6]]
------------------------------

Empilhando arrays horizontalmente
[[1 4]
 [2 5]
 [3 6]]
------------------------------



**Otimização de Desempenho:**

A função `numpy.vectorize` do NumPy permite converter funções Python em funções vetorizadas que operam em arrays NumPy. Isso pode ser extremamente útil para otimizar código complexo que envolve operações matemáticas em arrays, resultando em um aumento significativo na velocidade de execução.

In [2]:
import time
import numpy as np

def soma_simples(a, b):
  """
  Função simples para soma de dois elementos.
  """
  return a + b

# Criando arrays NumPy
a = np.random.rand(10_000_000)
b = np.random.rand(10_000_000)

# Medindo o tempo de execução do loop Python
start_time = time.time()
soma_loop = np.sum([soma_simples(x, y) for x, y in zip(a, b)])
end_time = time.time()
print(f"Tempo de loop Python: {end_time - start_time:.2f} segundos")

# Convertendo a função em vetorizada
soma_vetorizada = np.vectorize(soma_simples)

# Medindo o tempo de execução da função vetorizada
start_time = time.time()
soma_vetorizada = soma_vetorizada(a, b)
end_time = time.time()
print(f"Tempo da função vetorizada: {end_time - start_time:.2f} segundos")


Tempo de loop Python: 4.38 segundos
Tempo da função vetorizada: 3.20 segundos


## Função Mais Complexa com Otimização:
A otimização com numpy.vectorize é mais eficaz para funções que operam em arrays grandes e homogêneos.

Para funções com operações mais complexas ou com dependências entre elementos, outras técnicas de otimização podem ser necessárias.

É importante analisar o código e identificar as partes que podem

In [3]:
def funcao_complexa(x, y, z):
  """
  Função complexa que realiza operações matemáticas.
  """
  return np.exp(x) * np.log(y) + np.sqrt(z)

# Criando arrays NumPy
a = np.random.rand(1_000_000)
b = np.random.rand(1_000_000)
c = np.random.rand(1_000_000)

# Medindo o tempo de execução do loop Python
start_time = time.time()
resultado_loop = np.sum([funcao_complexa(x, y, z) for x, y, z in zip(a, b, c)])
end_time = time.time()
print(f"Tempo de loop Python: {end_time - start_time:.2f} segundos")

# Convertendo a função em vetorizada
funcao_vetorizada = np.vectorize(funcao_complexa)

# Medindo o tempo de execução da função vetorizada
start_time = time.time()
resultado_vetorizado = funcao_vetorizada(a, b, c)
end_time = time.time()
print(f"Tempo da função vetorizada: {end_time - start_time:.2f} segundos")


Tempo de loop Python: 3.50 segundos
Tempo da função vetorizada: 4.59 segundos
